version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: script-repo
    environment:
      POSTGRES_DB: ${DB_NAME:-myapp}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Load from .env file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: my_go_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: "postgres://postgres:password@postgres:5432/myapp?sslmode=disable"
      HTTPPORT: "8080"
      GRPCPORT: "9090"
    ports:
      - "8080:8080"  # HTTP port
      - "9090:9090"  # gRPC port

volumes:
  postgres_data:
