// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/transformer.proto

package transformerPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScriptIdentifier string                 `protobuf:"bytes,1,opt,name=script_identifier,json=scriptIdentifier,proto3" json:"script_identifier,omitempty"`
	Data             []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ValidateInput    bool                   `protobuf:"varint,3,opt,name=validate_input,json=validateInput,proto3" json:"validate_input,omitempty"`
	ValidateOutput   bool                   `protobuf:"varint,4,opt,name=validate_output,json=validateOutput,proto3" json:"validate_output,omitempty"`
	TimeoutSeconds   int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_api_proto_transformer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transformer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transformer_proto_rawDescGZIP(), []int{0}
}

func (x *TransformRequest) GetScriptIdentifier() string {
	if x != nil {
		return x.ScriptIdentifier
	}
	return ""
}

func (x *TransformRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransformRequest) GetValidateInput() bool {
	if x != nil {
		return x.ValidateInput
	}
	return false
}

func (x *TransformRequest) GetValidateOutput() bool {
	if x != nil {
		return x.ValidateOutput
	}
	return false
}

func (x *TransformRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      *TransformMetadata     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_api_proto_transformer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transformer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transformer_proto_rawDescGZIP(), []int{1}
}

func (x *TransformResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TransformResponse) GetMetadata() *TransformMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransformResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TransformMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScriptIdentifier string                 `protobuf:"bytes,1,opt,name=script_identifier,json=scriptIdentifier,proto3" json:"script_identifier,omitempty"`
	ScriptVersion    int32                  `protobuf:"varint,2,opt,name=script_version,json=scriptVersion,proto3" json:"script_version,omitempty"`
	ExecutionTimeMs  int64                  `protobuf:"varint,3,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	InputSize        int32                  `protobuf:"varint,4,opt,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	OutputSize       int32                  `protobuf:"varint,5,opt,name=output_size,json=outputSize,proto3" json:"output_size,omitempty"`
	CacheHit         bool                   `protobuf:"varint,6,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransformMetadata) Reset() {
	*x = TransformMetadata{}
	mi := &file_api_proto_transformer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformMetadata) ProtoMessage() {}

func (x *TransformMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transformer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformMetadata.ProtoReflect.Descriptor instead.
func (*TransformMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_transformer_proto_rawDescGZIP(), []int{2}
}

func (x *TransformMetadata) GetScriptIdentifier() string {
	if x != nil {
		return x.ScriptIdentifier
	}
	return ""
}

func (x *TransformMetadata) GetScriptVersion() int32 {
	if x != nil {
		return x.ScriptVersion
	}
	return 0
}

func (x *TransformMetadata) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *TransformMetadata) GetInputSize() int32 {
	if x != nil {
		return x.InputSize
	}
	return 0
}

func (x *TransformMetadata) GetOutputSize() int32 {
	if x != nil {
		return x.OutputSize
	}
	return 0
}

func (x *TransformMetadata) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

type CreateScriptRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScriptIdentifier string                 `protobuf:"bytes,1,opt,name=script_identifier,json=scriptIdentifier,proto3" json:"script_identifier,omitempty"`
	Script           string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	ValidateInput    bool                   `protobuf:"varint,3,opt,name=validate_input,json=validateInput,proto3" json:"validate_input,omitempty"`
	TimeoutSeconds   int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateScriptRequest) Reset() {
	*x = CreateScriptRequest{}
	mi := &file_api_proto_transformer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScriptRequest) ProtoMessage() {}

func (x *CreateScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transformer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScriptRequest.ProtoReflect.Descriptor instead.
func (*CreateScriptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transformer_proto_rawDescGZIP(), []int{3}
}

func (x *CreateScriptRequest) GetScriptIdentifier() string {
	if x != nil {
		return x.ScriptIdentifier
	}
	return ""
}

func (x *CreateScriptRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *CreateScriptRequest) GetValidateInput() bool {
	if x != nil {
		return x.ValidateInput
	}
	return false
}

func (x *CreateScriptRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateScriptRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScriptRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScriptResponse) Reset() {
	*x = CreateScriptResponse{}
	mi := &file_api_proto_transformer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScriptResponse) ProtoMessage() {}

func (x *CreateScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transformer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScriptResponse.ProtoReflect.Descriptor instead.
func (*CreateScriptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transformer_proto_rawDescGZIP(), []int{4}
}

func (x *CreateScriptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateScriptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_transformer_proto protoreflect.FileDescriptor

const file_api_proto_transformer_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/transformer.proto\x12\x0fjsontransformer\"\xcc\x01\n" +
	"\x10TransformRequest\x12+\n" +
	"\x11script_identifier\x18\x01 \x01(\tR\x10scriptIdentifier\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12%\n" +
	"\x0evalidate_input\x18\x03 \x01(\bR\rvalidateInput\x12'\n" +
	"\x0fvalidate_output\x18\x04 \x01(\bR\x0evalidateOutput\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\x81\x01\n" +
	"\x11TransformResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\".jsontransformer.TransformMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xf0\x01\n" +
	"\x11TransformMetadata\x12+\n" +
	"\x11script_identifier\x18\x01 \x01(\tR\x10scriptIdentifier\x12%\n" +
	"\x0escript_version\x18\x02 \x01(\x05R\rscriptVersion\x12*\n" +
	"\x11execution_time_ms\x18\x03 \x01(\x03R\x0fexecutionTimeMs\x12\x1d\n" +
	"\n" +
	"input_size\x18\x04 \x01(\x05R\tinputSize\x12\x1f\n" +
	"\voutput_size\x18\x05 \x01(\x05R\n" +
	"outputSize\x12\x1b\n" +
	"\tcache_hit\x18\x06 \x01(\bR\bcacheHit\"\xeb\x01\n" +
	"\x13CreateScriptRequest\x12+\n" +
	"\x11script_identifier\x18\x01 \x01(\tR\x10scriptIdentifier\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12%\n" +
	"\x0evalidate_input\x18\x03 \x01(\bR\rvalidateInput\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\"F\n" +
	"\x14CreateScriptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc5\x01\n" +
	"\x12TransformerService\x12R\n" +
	"\tTransform\x12!.jsontransformer.TransformRequest\x1a\".jsontransformer.TransformResponse\x12[\n" +
	"\fCreateScript\x12$.jsontransformer.CreateScriptRequest\x1a%.jsontransformer.CreateScriptResponseB\x19Z\x17api/proto/transformerPbb\x06proto3"

var (
	file_api_proto_transformer_proto_rawDescOnce sync.Once
	file_api_proto_transformer_proto_rawDescData []byte
)

func file_api_proto_transformer_proto_rawDescGZIP() []byte {
	file_api_proto_transformer_proto_rawDescOnce.Do(func() {
		file_api_proto_transformer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_transformer_proto_rawDesc), len(file_api_proto_transformer_proto_rawDesc)))
	})
	return file_api_proto_transformer_proto_rawDescData
}

var file_api_proto_transformer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_transformer_proto_goTypes = []any{
	(*TransformRequest)(nil),     // 0: jsontransformer.TransformRequest
	(*TransformResponse)(nil),    // 1: jsontransformer.TransformResponse
	(*TransformMetadata)(nil),    // 2: jsontransformer.TransformMetadata
	(*CreateScriptRequest)(nil),  // 3: jsontransformer.CreateScriptRequest
	(*CreateScriptResponse)(nil), // 4: jsontransformer.CreateScriptResponse
}
var file_api_proto_transformer_proto_depIdxs = []int32{
	2, // 0: jsontransformer.TransformResponse.metadata:type_name -> jsontransformer.TransformMetadata
	0, // 1: jsontransformer.TransformerService.Transform:input_type -> jsontransformer.TransformRequest
	3, // 2: jsontransformer.TransformerService.CreateScript:input_type -> jsontransformer.CreateScriptRequest
	1, // 3: jsontransformer.TransformerService.Transform:output_type -> jsontransformer.TransformResponse
	4, // 4: jsontransformer.TransformerService.CreateScript:output_type -> jsontransformer.CreateScriptResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_transformer_proto_init() }
func file_api_proto_transformer_proto_init() {
	if File_api_proto_transformer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_transformer_proto_rawDesc), len(file_api_proto_transformer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_transformer_proto_goTypes,
		DependencyIndexes: file_api_proto_transformer_proto_depIdxs,
		MessageInfos:      file_api_proto_transformer_proto_msgTypes,
	}.Build()
	File_api_proto_transformer_proto = out.File
	file_api_proto_transformer_proto_goTypes = nil
	file_api_proto_transformer_proto_depIdxs = nil
}
